"""Current retained matter/radiation sources -> asymptotically fixed GR input."""
from pathlib import Path
from types import FunctionType
import json,os,resource,signal,sys,time
import numpy as np
import def_retained_motion_return as previous
import def_native_characteristic_gr as wave
import verify_native_anisotropic_gr as constraints
import def_native_dynamic_lapse as metric

OUT=Path(os.environ.get('RETAINED_METRIC_OUTPUT','retained-metric-return152-work'))
BEFORE=Path('retained-motion-return151-work');NATIVE=previous.BEFORE
FIELDS=OUT/'fields';METRIC=OUT/'metric';PHOTON=OUT/'photons';MATERIAL=OUT/'material';GR=OUT/'gr'
read,write,sha=previous.read,previous.write,previous.sha;LD=np.longdouble;C=wave.C;G=wave.base.G;AMP=1e-26
CAPS=dict(fields=240,lapse=90,photon_pilot=80,photon_production=1000,material_pilot=50,material_production=350,readout=180,audit=60)


def prepare():
    assert not OUT.exists()
    for p in [OUT,FIELDS,METRIC/'corrected',PHOTON,MATERIAL,GR]:p.mkdir(parents=True,exist_ok=True)
    files=[Path(__file__),Path(previous.__file__),Path(wave.__file__),Path(wave.base.__file__),Path(metric.__file__),Path(constraints.__file__),
           BEFORE/'verification.json',BEFORE/'direct-motion/result.json',previous.prior.EV/'source-128.npz',previous.prior.EV/'accepted-ports-128.npz',previous.prior.EOS/'source.npz']
    for n in [64,128]:files += [NATIVE/f'gr/source-{n}-reference-128.npz',BEFORE/f'direct-motion/source-{n}.npz',BEFORE/f'photons/steps-{n}-reference-128.npz']
    write(OUT/'plan.json',dict(classification='Counterexample candidate',checkpoint='52f0828d0',
        claim='Apply the GR geometry generated by the CURRENT total retained material/radiation/native sources to actual photons and free material, then return that response to the same charge readout.',
        decision='Measure the missing metric-to-transport/material return rather than another constitutive source-only correction; keep the full EOS/background/final-charge objective open until its remaining errors are controlled.',
        source='Current full129-time background plus current129-time native EOS source, Phase150 response and Phase151 directly evaluated increment. Use the already established33-time characteristic source representation and exact17 outputs required by the saved state owner.',
        boundary='Current128 accepted background luminosity intervals plus the actual signed64/128 SDIRK photon packets. Fix lapse at infinity with the same exact scalar-vacuum ray model; do not clamp the numerical outer edge.',
        response='First metric variation on the saved corrected-EOS background, with separated sub-ulp geometry. Reuse existing photon/thermal/H tangent and branch-aware conservative material derivative. Finite current native defects generate the field, but their new-state native Jacobian and full nonlinear Einstein evolution remain open.',
        reuse='No background replay, native EOS calls, bank rebuild, new physical cells, frequencies, angles, response clocks or longer horizon. Keep64/128 only on the fine retained background; no native coarse-background certificate.',
        budgets=CAPS,total_max_seconds=sum(CAPS.values()),CPU_threads=1,virtual_GiB=3,
        gates=dict(field_quadrature=.002,full_history_outer=.002,time=.02,port=1e-12,ray=1e-10,linear=1e-12,
                   conservation=1e-8,material_directional=.002,physical_branch=.01,small_metric_response=1e-6,pressure=.002,independent_GR=1e-9),
        dispatch='Measure the first full33-time field, then require2x remaining fields plus20s inside240s. Measure actual4/8 photon prefixes and late-step floor before1000s. Use prior actual material raw-call counts and fresh2-step prefixes before350s. Reuse all accepted prefixes.',
        stop='Preserve any failed gate or forecast. No automatic finer clocks, cadence beyond the established33 source times, new domain, threshold relaxation or repeated full sweep.',
        limits='Initial-slice linear GR coefficients, finite cell/time/angle/frequency representation, fixed deeper incoming flux and incomplete exterior scalar scattering. This is an actual feedback application, not a coupled fixed-point or uniform physical error certificate.',
        bindings={str(p):sha(p) for p in files}))
    write(OUT/'symbolic.json',dict(classification='Proven',scope='Reused anisotropic first-variation constraint and zero-shift photon Hamiltonian identities only.',
        anisotropic=wave.base.symbolic(),null_transport=metric.symbolic(),characteristic=wave.check()))


def initialize():
    previous.initialize()
    wave.base.OUT=FIELDS;wave.OUT=FIELDS;constraints.OUT=FIELDS
    # All owners now use the actual retained low-density Capture via the shared flow module.
    assert wave.base.flow.Coupled is previous.prior.current.Capture


def blend(v,t,old_t):
    j=np.clip(np.searchsorted(old_t,t,side='right')-1,0,len(old_t)-2)
    f=(t-old_t[j])/(old_t[j+1]-old_t[j]);f=f.reshape((-1,)+(1,)*(v.ndim-1))
    return (1-f)*v[j]+f*v[j+1]


def inputs():
    base=dict(np.load(previous.prior.EV/'source-128.npz'));eos=np.load(previous.prior.EOS/'source.npz')
    keys=previous.prior.forcing.history.physical.capture.KEYS+['metric_stress_erg'];ports=['inner_cumulative_energy_erg','outer_cumulative_energy_erg']
    for n in [64,128]:
        old=np.load(NATIVE/f'gr/source-{n}-reference-128.npz');inc=np.load(BEFORE/f'direct-motion/source-{n}.npz')
        for stride,label in [(4,str(n)),(8,f'{n}-17')]:
            t=base['t'][::stride];d={k:(v[::stride].copy() if v.ndim and v.shape[0]==129 else v.copy()) for k,v in base.items()}
            for k in keys:d[k]=d[k]+eos[k][::stride]+blend(old[k]+inc[k],t,old['t'])
            for k in ports:d[k]=d[k]+blend(old[k]+inc[k],t,old['t'])
            # The outer packet port has every accepted stage, so use it exactly even between the17 saved states.
            p=np.load(BEFORE/f'photons/steps-{n}-reference-128.npz');gamma=1-1/np.sqrt(2);h=t[-1]/n
            packet=h*np.tile([1-gamma,gamma],n)[:,None]*p['accepted_angular_luminosity']
            cumulative=np.r_[0.,np.cumsum(packet@(np.arange(1,8,2)/32),dtype=LD)]
            d['outer_cumulative_energy_erg']=base['outer_cumulative_energy_erg'][::stride]+cumulative[2*np.rint(t/h).astype(int)]
            np.savez_compressed(FIELDS/f'source-{label}.npz',**d)


def fields():
    start=time.monotonic();inputs();m=wave.Response()
    fn=FunctionType(wave.Response.run.__code__,dict(wave.Response.run.__globals__,OUT=FIELDS))
    mark=time.monotonic();rows=[fn(m,128,8)];first=time.monotonic()-mark;forecast=2*first*2.5+20
    write(FIELDS/'pilot.json',dict(classification='Counterexample candidate',first_seconds=first,remaining_upper_seconds=forecast,eligible=forecast<240-(time.monotonic()-start)))
    assert forecast<240-(time.monotonic()-start)
    for n,q in [(64,8),(128,4),('128-17',8)]:rows.append(fn(m,n,q))
    fine=np.load(FIELDS/'fields-128-g8.npz');norm=max(np.max(abs(fine['U'])),1e-300)
    errors={k:float(np.max(abs(fine['U']-np.load(FIELDS/f'fields-{n}-g{q}.npz')['U']))/norm) for k,n,q in [('response_time',64,8),('quadrature',128,4)]}
    target=np.load(previous.prior.EOS/'applied-charge.npz')['free_scalar'][::8]+np.load(NATIVE/'gr/wave-128-g8.npz')['free_scalar']+np.load(BEFORE/'direct-motion/wave-128-g8.npz')['free_scalar']
    actual=-fine['direct_and_mass_stress_U'][::2,-1]/float(m.data['M_cm'])
    errors['full_history_outer']=float(np.max(abs(actual-target))/max(np.max(abs(target)),1e-300))
    coarse=np.load(FIELDS/'fields-128-17-g8.npz')
    cadence=float(np.max(abs(fine['U'][::2]-coarse['U']))/norm)
    passed=errors['response_time']<.02 and errors['quadrature']<.002 and errors['full_history_outer']<.002
    result=dict(classification='Counterexample candidate',passed=passed,errors=errors,diagnostic17_33_cadence=cadence,rows=rows,
        seconds=time.monotonic()-start,full_current_source_applied=True,physical_history_replayed=False,full_goal_complete=False)
    write(FIELDS/'result.json',result);print(json.dumps(result),flush=True);assert passed


class Lapse(metric.Lapse):
    run=FunctionType(metric.Lapse.run.__code__,dict(metric.Lapse.run.__globals__,OUT=METRIC))
    def boundary(self,d,steps,order):
        t=d['t'];end=t[-1];mu,mw,ids,solution,invariant=self.rays(order,end)
        background=np.load(previous.prior.EV/'accepted-ports-128.npz');lum=background['angular_luminosity'];h=float(background['h'])
        p=np.load(BEFORE/f'photons/steps-{steps}-reference-128.npz');gamma=1-1/np.sqrt(2);hp=end/steps
        packets=hp*np.tile([1-gamma,gamma],steps)[:,None]*p['accepted_angular_luminosity'];stage=p['accepted_angular_times']
        gx,gw=np.polynomial.legendre.leggauss(order);photon=[];energy=[]
        for now in t:
            count=int(round(now/h));n=int(round(now/hp))*2
            if count==0:photon.append(0.);energy.append(0.);continue
            tt=((np.arange(count)[:,None]+(gx+1)/2)*h).ravel()
            weight=((h*gw/2)[None,:,None]*lum[:count,None,ids]*mu*mw).reshape(len(tt),len(mu))
            tt=np.r_[tt,stage[:n]];weight=np.concatenate([weight,packets[:n,ids]*mu*mw])
            ages=np.maximum((now-tt)/end,0.)
            state=solution.sol(ages).reshape(3,len(mu),len(tt)).transpose(0,2,1)
            rp=self.r0*state[0];mp=state[1];cc=self.bg.metric(rp.ravel()/self.model.m.R)[3].reshape(rp.shape)
            kernel=state[2]/self.r0-mp*mp/(rp*cc)
            photon.append(float(G/C**4*np.sum(weight*kernel,dtype=LD)));energy.append(float(np.sum(weight,dtype=LD)))
        energy=np.array(energy);photon=np.array(photon)
        error=float(np.max(abs(energy-d['outer_cumulative_energy_erg']))/max(np.max(abs(energy)),1.));assert error<1e-12
        z=(gx+1)/2;_,N,b,_,_=self.bg.metric(self.r0/(z*self.model.m.R));kernel=float(np.sum(gw/(2*self.r0*N*b**1.5)))
        return photon,energy,dict(ray_invariant=invariant,emitted_energy_relative=error,unit_ADM_lapse_kernel_per_cm=kernel,actual_background_intervals_and_SDIRK_packets=True)


def lapse():
    assert read(FIELDS/'result.json')['passed'];m=Lapse();rows=[]
    for n,q in [(128,8),(64,8),(128,4)]:
        rows.append(m.run(n,q));z=dict(np.load(METRIC/f'metric-{n}-g{q}.npz'))
        z={k:(v[::2] if v.ndim and v.shape[0]==33 else v) for k,v in z.items()}
        z['delta_lambda_interval_rate']=np.diff(z['delta_lambda'],axis=0)/np.diff(z['t'])[:,None]
        z['delta_nu_interval_rate']=np.diff(z['delta_nu'],axis=0)/np.diff(z['t'])[:,None]
        np.savez_compressed(METRIC/f'corrected/metric-{n}-g{q}.npz',**z)
    fine=np.load(METRIC/'corrected/metric-128-g8.npz');errors={}
    for key,n,q in [('response_time',64,8),('quadrature',128,4)]:
        other=np.load(METRIC/f'corrected/metric-{n}-g{q}.npz')
        errors[key]={name:float(np.max(abs(fine[name]-other[name]))/max(np.max(abs(fine[name])),1e-300)) for name in ['delta_u','delta_lambda','delta_log_lapse','delta_log_speed']}
    passed=max(errors['response_time'].values())<.02 and max(errors['quadrature'].values())<.002 and max(r['ray_invariant'] for r in rows)<1e-10
    result=dict(classification='Counterexample candidate',passed=passed,errors=errors,rows=rows,full_current_metric_ready=True,metric_applied_to_evolution=False,full_goal_complete=False)
    write(METRIC/'result.json',result);print(json.dumps(result),flush=True);assert passed


if __name__=='__main__':
    action=sys.argv[1]
    if action=='prepare':prepare()
    else:
        assert not (OUT/f'{action}-receipt.json').exists()
        resource.setrlimit(resource.RLIMIT_AS,(3*1024**3,3*1024**3))
        def timeout(*_):raise TimeoutError('Registered field/lapse budget')
        signal.signal(signal.SIGALRM,timeout);signal.alarm(CAPS[action]);start=time.monotonic();cpu=time.process_time();error=None
        try:
            for p,h in read(OUT/'plan.json')['bindings'].items():assert sha(p)==h,p
            initialize();globals()[action]()
        except Exception as exc:error=repr(exc);raise
        finally:
            signal.alarm(0);write(OUT/f'{action}-receipt.json',dict(seconds=time.monotonic()-start,CPU_seconds=time.process_time()-cpu,error=error,source_sha256=sha(__file__)))
