from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import sympy as sp

from frequency_sweep_distinguishability import ALLOWED_CLAIM_STATUSES


REPO_ROOT = Path(__file__).resolve().parents[1]
TSV_PATH = (
    REPO_ROOT
    / "outputs"
    / "tsv"
    / "dynamic_chi_triple_projection_nuisance_gate.tsv"
)
JSON_PATH = (
    REPO_ROOT
    / "outputs"
    / "json"
    / "dynamic_chi_triple_projection_nuisance_gate.json"
)

GATE_COLUMNS = (
    "term",
    "claim_status",
    "carrier_set",
    "projection_nuisance_class",
    "nuisance_parameterization",
    "nuisance_dimension",
    "comparator_pressure",
    "bridge_verdict",
    "runtime_relevance",
    "notes",
)

ALLOWED_BRIDGE_VERDICTS = {"distinguishable", "conditional", "collapse"}
ALLOWED_RUNTIME_RELEVANCE = {
    "runtime-motivated",
    "conditional",
    "not-runtime-motivated",
}


@dataclass(frozen=True)
class ProjectionGateRow:
    term: str
    claim_status: str
    carrier_set: str
    projection_nuisance_class: str
    nuisance_parameterization: str
    nuisance_dimension: str
    comparator_pressure: str
    bridge_verdict: str
    runtime_relevance: str
    notes: str

    def __post_init__(self) -> None:
        if self.claim_status not in ALLOWED_CLAIM_STATUSES:
            allowed = ", ".join(sorted(ALLOWED_CLAIM_STATUSES))
            raise ValueError(
                f"claim_status must be one of {allowed}; got {self.claim_status!r}"
            )
        if self.bridge_verdict not in ALLOWED_BRIDGE_VERDICTS:
            allowed = ", ".join(sorted(ALLOWED_BRIDGE_VERDICTS))
            raise ValueError(
                f"bridge_verdict must be one of {allowed}; "
                f"got {self.bridge_verdict!r}"
            )
        if self.runtime_relevance not in ALLOWED_RUNTIME_RELEVANCE:
            allowed = ", ".join(sorted(ALLOWED_RUNTIME_RELEVANCE))
            raise ValueError(
                f"runtime_relevance must be one of {allowed}; "
                f"got {self.runtime_relevance!r}"
            )

    def to_row(self) -> dict[str, str]:
        return asdict(self)


def symbols() -> dict[str, sp.Symbol]:
    names = (
        "z tau_chi beta c_Y F_hat O_hat Gamma kappa "
        "q_k g0 g1 ell0 ell1"
    )
    return {name: sp.Symbol(name, nonzero=True) for name in names.split()}


def relaxation_transfer() -> sp.Expr:
    sym = symbols()
    return sym["c_Y"] + sym["beta"] / (1 + sym["tau_chi"] * sym["z"])


def projection_model_forms() -> dict[str, str]:
    return {
        "calibrated_common_real_scale": "Lambda_k(theta)=Gamma",
        "finite_real_shared_geometry": "Lambda_k(theta)=g0+g1 q_k",
        "range_like_shared_projection": "Lambda_k(theta)=Gamma/(kappa^2+z_k^2)",
        "finite_complex_shared_polynomial": "Lambda_k(theta)=ell0+ell1 z_k",
        "arbitrary_per_carrier_complex": "Lambda_k independent for each carrier",
        "zero_or_singular_projection": "Lambda_k=0 or Lambda_k singular on a carrier",
    }


def triple_projection_mapping() -> dict[str, str]:
    return {
        "carriers": "Omega_in, Omega_out, abs(Omega_in-Omega_out)",
        "sample_nodes": "z_k=i Omega_k",
        "dynamic_transfer": "G(z)=c_Y+beta/(1+tau_chi z)",
        "observed_carrier": "O_k=Lambda_k(theta) G(z_k) F_k",
        "finite_projection_condition": (
            "Lambda_k is generated by a shared low-dimensional theta, not by "
            "independent complex amplitudes at each carrier"
        ),
    }


def calibrated_deprojection_residual() -> sp.Expr:
    sym = symbols()
    observed = sym["Gamma"] * relaxation_transfer() * sym["F_hat"]
    deprojected = sp.simplify(observed / (sym["Gamma"] * sym["F_hat"]))
    return sp.factor(sp.simplify(deprojected - relaxation_transfer()))


def range_deprojection_residual() -> sp.Expr:
    sym = symbols()
    projection = sym["Gamma"] / (sym["kappa"] ** 2 + sym["z"] ** 2)
    observed = projection * relaxation_transfer() * sym["F_hat"]
    deprojected = sp.simplify(
        observed * (sym["kappa"] ** 2 + sym["z"] ** 2)
        / (sym["Gamma"] * sym["F_hat"])
    )
    return sp.factor(sp.simplify(deprojected - relaxation_transfer()))


def arbitrary_projection_solution() -> sp.Expr:
    sym = symbols()
    return sp.simplify(sym["O_hat"] / (relaxation_transfer() * sym["F_hat"]))


def arbitrary_projection_reconstruction_residual() -> sp.Expr:
    sym = symbols()
    lambda_solution = arbitrary_projection_solution()
    reconstructed = sp.simplify(
        lambda_solution * relaxation_transfer() * sym["F_hat"]
    )
    return sp.factor(sp.simplify(reconstructed - sym["O_hat"]))


def nuisance_dimension_ledger() -> dict[str, str]:
    return {
        "three_carrier_observable_vector": "3 complex samples = 6 real numbers",
        "calibrated_common_real_scale": "0 fitted projection nuisance after calibration",
        "common_real_scale_unknown": "1 real shared nuisance",
        "finite_real_shared_geometry": "finite real d << 6, shared by all carriers",
        "range_like_shared_projection": "2 real shared nuisance parameters Gamma,kappa",
        "finite_complex_shared_polynomial_degree1": "2 complex shared nuisance parameters",
        "arbitrary_per_carrier_complex": "3 complex nuisance parameters = 6 real numbers",
    }


def gate_rows() -> list[ProjectionGateRow]:
    carriers = "Omega_in, Omega_out, abs(Omega_in-Omega_out)"
    return [
        ProjectionGateRow(
            term="calibrated_common_real_scale",
            claim_status="Counterexample candidate",
            carrier_set=carriers,
            projection_nuisance_class="calibrated finite real projection",
            nuisance_parameterization="Lambda_k=Gamma, known or externally calibrated",
            nuisance_dimension="0 fitted projection nuisance after calibration",
            comparator_pressure="three-carrier pressure remains real N<=4, complex N<=1",
            bridge_verdict="distinguishable",
            runtime_relevance="runtime-motivated",
            notes=(
                "A calibrated common scale deprojects all carriers to the same "
                "shared G(z_k), so the Request 10.3 bridge is preserved."
            ),
        ),
        ProjectionGateRow(
            term="common_real_scale_unknown",
            claim_status="Counterexample candidate",
            carrier_set=carriers,
            projection_nuisance_class="finite real projection nuisance",
            nuisance_parameterization="Lambda_k=Gamma, one unknown shared real scale",
            nuisance_dimension="1 real shared nuisance",
            comparator_pressure="ratios across carriers remove the common scale",
            bridge_verdict="distinguishable",
            runtime_relevance="runtime-motivated",
            notes=(
                "One shared real scale cannot absorb carrier-by-carrier phase "
                "or frequency dependence; it cancels in transfer ratios."
            ),
        ),
        ProjectionGateRow(
            term="finite_real_shared_geometry",
            claim_status="Counterexample candidate",
            carrier_set=carriers,
            projection_nuisance_class="finite-dimensional real projection nuisance",
            nuisance_parameterization="Lambda_k=g0+g1 q_k with known carrier geometry q_k",
            nuisance_dimension="2 real shared nuisance parameters in this template",
            comparator_pressure=(
                "not pointwise arbitrary, but consumes rank and needs explicit "
                "Jacobian or prior audit"
            ),
            bridge_verdict="conditional",
            runtime_relevance="conditional",
            notes=(
                "Shared geometry links the three carrier projections. The bridge "
                "does not collapse algebraically, but a full rank/prior check is "
                "needed before calling it observable."
            ),
        ),
        ProjectionGateRow(
            term="range_like_shared_projection_unknown",
            claim_status="Counterexample candidate",
            carrier_set=carriers,
            projection_nuisance_class="finite-dimensional real projection nuisance",
            nuisance_parameterization="Lambda_k=Gamma/(kappa^2+z_k^2)",
            nuisance_dimension="2 real shared nuisance parameters Gamma,kappa",
            comparator_pressure=(
                "survives if Gamma,kappa are calibrated, shared, or constrained "
                "by additional carriers"
            ),
            bridge_verdict="conditional",
            runtime_relevance="conditional",
            notes=(
                "This is the concrete projection-channel audit lifted to the "
                "triple carrier set. Unknown shared projection parameters make "
                "the result prior- and rank-dependent."
            ),
        ),
        ProjectionGateRow(
            term="finite_complex_shared_polynomial",
            claim_status="Counterexample candidate",
            carrier_set=carriers,
            projection_nuisance_class="finite-dimensional complex projection nuisance",
            nuisance_parameterization="Lambda_k=ell0+ell1 z_k, shared coefficients",
            nuisance_dimension="2 complex shared nuisance parameters",
            comparator_pressure=(
                "overpowered but still shared; three carriers are insufficient "
                "for high complex projection/comparator order"
            ),
            bridge_verdict="conditional",
            runtime_relevance="conditional",
            notes=(
                "A shared complex projection is not the same as arbitrary "
                "per-carrier freedom, but it can absorb enough structure that "
                "more carriers or a projection prior are required."
            ),
        ),
        ProjectionGateRow(
            term="arbitrary_per_carrier_complex_projection",
            claim_status="Proven",
            carrier_set=carriers,
            projection_nuisance_class="arbitrary complex projection nuisance",
            nuisance_parameterization="Lambda_k free independently for each carrier",
            nuisance_dimension="3 complex nuisance parameters = 6 real numbers",
            comparator_pressure="none; each observed carrier is fit pointwise",
            bridge_verdict="collapse",
            runtime_relevance="not-runtime-motivated",
            notes=(
                "Choosing Lambda_k=O_k/(G(z_k) F_k) absorbs the shared transfer "
                "law at each carrier. This is the conservative collapse boundary."
            ),
        ),
        ProjectionGateRow(
            term="zero_or_singular_projection",
            claim_status="Proven",
            carrier_set=carriers,
            projection_nuisance_class="blind or singular projection",
            nuisance_parameterization="Lambda_k=0, undefined, or pole-cancelling",
            nuisance_dimension="not applicable",
            comparator_pressure="carrier sample lost",
            bridge_verdict="collapse",
            runtime_relevance="not-runtime-motivated",
            notes=(
                "A carrier with zero projection, a singular deprojection, or a "
                "projection zero at the relaxation pole cannot support the "
                "shared-tau bridge."
            ),
        ),
        ProjectionGateRow(
            term="realistic_projection_gate_summary",
            claim_status="Conjectural",
            carrier_set=carriers,
            projection_nuisance_class="realistic triple timing projection manifold",
            nuisance_parameterization="finite shared geometry parameters preferred",
            nuisance_dimension="model-dependent finite rank",
            comparator_pressure=(
                "runtime-worthy only if the projection manifold is finite and "
                "not equivalent to independent complex amplitudes"
            ),
            bridge_verdict="conditional",
            runtime_relevance="conditional",
            notes=(
                "Request 10.4 does not claim a measured observable. It states "
                "the gate: finite shared projection can preserve the dynamic-chi "
                "bridge, arbitrary per-carrier projection kills it."
            ),
        ),
    ]


def rows_as_dicts() -> list[dict[str, str]]:
    return [row.to_row() for row in gate_rows()]


def validate_rows(rows: Iterable[dict[str, str]]) -> None:
    expected = set(GATE_COLUMNS)
    for index, row in enumerate(rows, start=1):
        actual = set(row)
        if actual != expected:
            raise ValueError(
                f"row {index} has columns {sorted(actual)}, "
                f"expected {sorted(expected)}"
            )
        if row["claim_status"] not in ALLOWED_CLAIM_STATUSES:
            raise ValueError(f"row {index} has invalid claim_status")
        if row["bridge_verdict"] not in ALLOWED_BRIDGE_VERDICTS:
            raise ValueError(f"row {index} has invalid bridge_verdict")
        if row["runtime_relevance"] not in ALLOWED_RUNTIME_RELEVANCE:
            raise ValueError(f"row {index} has invalid runtime_relevance")
        if not all(str(row[column]).strip() for column in GATE_COLUMNS):
            raise ValueError(f"row {index} contains an empty field")


def payload() -> dict[str, object]:
    rows = rows_as_dicts()
    validate_rows(rows)
    return {
        "schema": list(GATE_COLUMNS),
        "assumptions": {
            "model": "tau_chi dot chi + chi = alpha F(t)",
            "transfer": "G(z)=c_Y+beta/(1+tau_chi z)",
            "carrier_set": "Omega_in, Omega_out, abs(Omega_in-Omega_out)",
            "scope": "symbolic projection-nuisance realism gate; no runtime",
        },
        "projection_mapping": triple_projection_mapping(),
        "projection_model_forms": projection_model_forms(),
        "nuisance_dimension_ledger": nuisance_dimension_ledger(),
        "calibrated_deprojection_residual": sp.sstr(calibrated_deprojection_residual()),
        "range_deprojection_residual": sp.sstr(range_deprojection_residual()),
        "arbitrary_projection_solution": sp.sstr(arbitrary_projection_solution()),
        "arbitrary_projection_reconstruction_residual": sp.sstr(
            arbitrary_projection_reconstruction_residual()
        ),
        "verdict_meaning": {
            "distinguishable": (
                "the three-carrier shared-tau bridge survives this projection "
                "class at the symbolic gate level"
            ),
            "conditional": (
                "finite shared nuisance does not collapse pointwise, but a "
                "rank/prior audit is required"
            ),
            "collapse": (
                "the projection nuisance can erase the shared transfer law or "
                "remove the carrier sample"
            ),
        },
        "runtime_relevance_meaning": {
            "runtime-motivated": (
                "external timing runtime is scientifically justified if the "
                "carrier amplitudes exist and this projection class is valid"
            ),
            "conditional": "needs projection priors, more carriers, or a rank audit first",
            "not-runtime-motivated": "symbolic gate already collapses",
        },
        "rows": rows,
    }


def write_outputs(data: dict[str, object] | None = None) -> None:
    data = data or payload()
    rows = data["rows"]
    if not isinstance(rows, list):
        raise TypeError("payload rows must be a list")

    TSV_PATH.parent.mkdir(parents=True, exist_ok=True)
    with TSV_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=GATE_COLUMNS, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)

    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(
        json.dumps(data, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    data = payload()
    write_outputs(data)
    print(f"calibrated_deprojection_residual: {data['calibrated_deprojection_residual']}")
    print(
        "arbitrary_projection_reconstruction_residual: "
        f"{data['arbitrary_projection_reconstruction_residual']}"
    )
    print(f"wrote {TSV_PATH}")
    print(f"wrote {JSON_PATH}")


if __name__ == "__main__":
    main()
