#!/bin/bash
LOG_FILE="./out"
function onexit {
	date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
	T="$(($(date +%s)-T))"

	if [ $T -gt 86400 ]; then
		D=0
		while [ $T -gt 86400 ];do
			T=$(echo "$T - 86400" | bc)
			#T= T - 86400
			D=$(echo "$D + 1" | bc)
		done

		date -ud @$T "+Execution time: $D days and %H:%M:%S"
                exec date -ud @$T "+Execution time: $D days and %H:%M:%S" >> $LOG_FILE
	else
		date -ud @$T "+Execution time: %H:%M:%S"
                exec date -ud @$T "+Execution time: %H:%M:%S" >> $LOG_FILE
	fi
}
function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

function check_rsfile {
	restart_file="./photos1/$1"

	if [ ! -f $restart_file ]; then
	        echo $restart_file
		echo "the file does not exist so  a restart is not possible!"
	        exit 1
	fi
}
check_rsfile $1

echo $1 > .restart
check_okay

T="$(date +%s)"
trap onexit TERM QUIT EXIT

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
if [[ -e star.exe ]];then
	./star.exe | tee -a out
else
	./binary | tee -a out
fi
