# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/home/lpaiu/work/nutimo_pilot/request14_capd/capdExt/include -I/home/lpaiu/work/nutimo_pilot/request14_capd/capdAux/include -I/home/lpaiu/work/nutimo_pilot/request14_capd/capdAlg/include -I/home/lpaiu/work/nutimo_pilot/request14_capd/capdDynSys/include -I/home/lpaiu/work/nutimo_pilot/request14_capd/capdExt/filibsrc

CXX_FLAGS = -O3 -DNDEBUG -O2 -frounding-math -D__USE_FILIB__ -DFILIB_HAVE_SSE

