#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


echo 'create ionization_data'

rm -rf ionization_data

cp test/ionization_data.tar.bz2 .
check_okay

echo 'bzip2 -d ionization_data.tar.bz2'
bzip2 -d ionization_data.tar.bz2
check_okay

tar -xvf ionization_data.tar
check_okay
rm ionization_data.tar

rm -rf ../data/ionization_data
check_okay

mkdir ../data/ionization_data
check_okay

mv ionization_data/*.data ../data/ionization_data
check_okay

mkdir ../data/ionization_data/cache
check_okay

echo "done"

