from pathlib import Path
from decimal import Decimal,localcontext
import hashlib,json,py_compile,shutil,subprocess,sys
root=Path('E:/lab/self-mass-unobservability')
runtime=Path('//wsl.localhost/Ubuntu-22.04/home/lpaiu/work/native-retained-tail-runtime')
work=runtime/'native-incident-self-gr157-work';out=root/'outputs/direct-eos-gr33/native-incident-self-gr'
manifest=out.parent/'native-incident-self-gr-manifest.json';master=root/'paper/revision-manifest.json'
note=root/'notes/REQUEST157_INCIDENT_SELF_GR_RETURN_KO.md'
modules=['solve_native_incident_self_gr','audit_native_incident_self_gr']
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):
    with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def write(p,v):p.write_bytes((json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode())


def package(sweep):
    assert not manifest.exists() and not note.exists()
    final=read(work/'result.json');audit=read(work/'audit.json');block=read(work/'block-result.json')
    assert final['passed'] and final['finite_self_metric_residual_passed'] and audit['passed'] and block['passed']
    assert not final['full_goal_complete'] and final['actual_self_GR_returned']
    # The reused reader's historical labels describe the original incident run.
    # This canonical result identifies the separately normalized self-GR input.
    final['normalized_endpoint_over_reference_eta']=final.pop('endpoint_over_incident_amplitude')
    final['physical_correction_over_incident_amplitude']=final['physical_self_GR_correction_endpoint']/final['incident_amplitude']
    final['actual_external_input_consumed']=False
    final['external_input_consumed_by_baseline']=True
    final['compact_return_endpoint_units']='Normalized self-GR increment; physical value is physical_self_GR_correction_endpoint.'
    ph=read(work/f'sweep-{sweep}/photons-common-gr/result.json');mat=read(work/f'sweep-{sweep}/material-common-gr/production.json')
    src=read(work/f'sweep-{sweep}/material-common-gr/sources.json');res=read(work/f'sweep-{sweep}/residual.json')
    assert all(x['passed'] for x in [ph,mat,src,res]) and not res['finite_reciprocal_residual_passed']
    assert block['original_stop_preserved'] and not block['original_waveform_change_test_passed']
    res['self_GR_returned']=True
    res['self_GR_scope']='Common prescribed fine GR generated by the Phase156 response; raw inherited parent labels remain archived.'
    before=sha(master);data=read(master);old=read(out.parent/'native-incident-reciprocal-manifest.json');preserved=0
    for name,h in old['sha256'].items():
        if not name.startswith('docs/'):assert sha(root/name)==h,name;preserved+=1
    for m in modules:
        p=root/f'verification/{m}.py';assert sha(p)==sha(runtime/f'verification/{m}.py');py_compile.compile(str(p),doraise=True)
    versions={sha(p):p.name for p in work.glob('*.py')}
    versions.update({sha(root/f'verification/{m}.py'):f'verification/{m}.py' for m in modules})
    receipts={p.name:read(p) for p in work.rglob('*-receipt.json')}
    for k,v in receipts.items():assert v['source_sha256'] in versions,(k,v['source_sha256'])
    cost=dict(recorded_action_seconds=sum(v['seconds'] for v in receipts.values()),CPU_seconds=sum(v['CPU_seconds'] for v in receipts.values()),
        peak_RSS_bytes=max(v['peak_RSS_bytes'] for v in receipts.values()),CPU_threads=1,virtual_GiB=3,
        scope='Recorded action bodies including failed prefixes; excludes imports, inspection, writing, publication and Git. Not total task time.')
    assert cost['recorded_action_seconds']<4600
    dest=out/'completed';dest.mkdir(parents=True);copies={};omitted={};size=0
    for p in work.rglob('*'):
        if not p.is_file():continue
        assert not p.is_symlink();rel=p.relative_to(work)
        if p.name.endswith('-checkpoint.npz'):
            assert (p.parent/p.name.replace('-checkpoint.npz','.npz')).exists()
            omitted[rel.as_posix()]=sha(p);continue
        q=dest/rel;q.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,q)
        assert sha(p)==sha(q);copies[rel.as_posix()]=sha(q);size+=q.stat().st_size
    shutil.copyfile(__file__,out/'publication-producer.py')
    write(out/'publication.json',dict(copies=copies,bytes=size,omitted_terminal_checkpoints=omitted,
        receipt_source_versions={k:versions[v['source_sha256']] for k,v in receipts.items()}))
    with localcontext() as ctx:
        ctx.prec=80;total=str(Decimal(str(final['baseline_compact_endpoint']))+Decimal(str(final['physical_self_GR_correction_endpoint'])))
    result=dict(classification='Counterexample candidate',passed=True,full_goal_complete=False,compact_GR=final,
        compensated_endpoint=dict(baseline=final['baseline_compact_endpoint'],correction=final['physical_self_GR_correction_endpoint'],decimal_sum=total,
            scope='Arithmetic sum of the recorded numerical estimates; extra digits are not physical accuracy.'),
        photon=ph,material=mat,sources=src,residual=res,block_coupling=block,audit=audit,cost=cost,
        original_different_GR_prefix_verdict='failed',upstream_GR_uncertainty_closed=False,
        original_waveform_change_test_passed=False,accepted_scope='Fixed-input finite block-equation consistency and compact readout only.',
        contribution='Conditional loophole progress at one common fine GR input: return the generated metric to photon/material evolution and read compact charge after direct lagged-input/stage-source and metric residual checks. Original different-input and whole-state monotonicity tests remain failed; no third evolution was performed.')
    write(out/'final-result.json',result)
    rows=[read(work/f'sweep-{i}/residual.json') for i in range(1,sweep+1)]
    table='\n'.join(f"| {i+1} | {100*r['maximum_residual']:.9g}% |" for i,r in enumerate(rows))
    text=f'''# 단계157 — 실제 입사 응답의 자체 GR 반환

분류: Counterexample candidate. **단계156의 정밀128 경로 원천이 만드는 스칼라·질량·lapse를 실제 진화식에 다시 적용했다.** 동일 입력 아래64/128 광자·열·H와 자유 물질을 두 번 반환했다. 기존 전체 상태 변화의 감소 기준은 실패해 반복을 중단했다. 이후 별도 등록한 실제 전달 입력·모든 단계 원천의 식 일치 검사를 통과한 해에서 compact 전하를 읽고 자체 계량 잔차를 확인했다. 서로 다른 상위 GR 입력의 초기 시간 실패와 전체 상태 변화 실패는 모두 보존한다. 이번 결과는 고정된 정밀 GR 입력의 유한 블록 식에 조건부인 loophole progress이며 전체 목표는 미완료다.

분류: Counterexample candidate. 기존 531셀·8각도·152주파수·3.4344311179ms·64/128 경로와 17개 파형 절점을 유지했다. 수정된 EOS의 저장 배경과 은행을 재사용했고 배경 진화를 다시 계산하지 않았다. 외부 lapse에는 실제 signed SDIRK 광자 방출만 넣었다. 원래 배경 광도나 외부 입사파를 중복 주입하지 않았다. 초기 GR 계수, leading 외부 스칼라 lapse, 유한 보간 범위는 유지된다.

분류: Proven. 고정된 선형 연산자에서 양의 상수 배율로 입력·응답을 함께 바꾸고 나중에 나누는 것은 같은 선형 문제다. 기호 항등식·기존 제약/광자 Hamiltonian 검사를 통과했다. HLL/donor의 모든 방향에서 선형성이 성립한다는 증명은 아니다.

분류: Counterexample candidate. 자체 계량의 최대 무차원 성분은 6.59957661336e-50이다. 이를 2^63배 정규화해 별도 증분을 계산했으며, 실제 전하 보정은 그 배율로 나눴다. 광자 증분에는 기존 입사파의 affine lift를 다시 넣지 않았다. 실제 물질 방향의 초기·중간·끝점 양의 동차성과 원 입사 응답 방향과의 합성을 별도로 검사했다. 표본 미분·분기 검사 범위이며 전체 EOS/Jacobian의 균일 인증은 아니다.

분류: Counterexample candidate. 첫 시범의 GMRES는 잔차3.42913e-14에서 정체했고, 잔차만 확장 정밀도로 바꾸는 수리도2.09735e-14에서 멈췄다. 보정된 단계 상태를 binary64로 다시 반올림하는 것이 남은 병목이었다. 단계 상태와 잔차를 longdouble로 유지하고, 기존 binary64 Krylov 풀이를 보정 방정식에 재사용했다. 내부1e-14·전체 식1e-12·보존1e-8 기준을 유지했고 시범부터 다시 통과했다. 두 원 실패는 보존했다. 통과한 시범 저장 후의 NumPy JSON 출력 오류는 출력 경계에서만 수정했으며 시범을 재계산하지 않았다.

분류: Counterexample candidate. 첫 전체 광자 경로의 방사압 시간 차이2.25741061%는2% 기준에 실패했다. 원인은 저장 시각보다1ulp 큰 종료 시각이 다음 구간의 계량 미분을 선택한 경우였다.64단계에서4곳,128단계에서2곳을 찾았고 실제 원천 차이가 각도·주파수의 시간 미분 점프로 설명됨을1.3e-15 이내로 확인했다. 물질 적분기와 같은16ulp 저장 시각 정렬을 광자 원천에 적용했다. 기존4/8 시범의 모든 stage 시각은 실제로 변하지 않음을 확인해 바이트 그대로 재사용했다. 잘못된 전체 이력은 보존하고 영향을 받는 뒤 구간만 다시 계산했다. 새 격자나 완화된 수락 기준은 사용하지 않았다. 예측 wrapper의 초기화 순서 오류1건은 적분 전 실패였으며 실행 경로만 수정했다.

분류: Counterexample candidate. 물질·광자 잔차는 Etilde 좌표의 충돌/기계적 일 분리를 유지한 실제 파형 반환 차이다. 0.2% 기준, 최대3회, 둘째 반환 이후 비감소 시 중단 조건을 먼저 등록했다.

분류: Counterexample candidate. 두 번째 광자 반환의 초기 에너지·압력 시간 비교는44.7/45.1%로 실패했다. 이전 자유 물질의 첫 저장 구간 에너지도46.01%, 운동량은27.29% 달랐다. 같은 시간 격자의 SSPRK3 시범은 이를 개선하지 못해 폐기했다. 실제 원인은 비교 대상 두 경로가 서로 다른 상위 GR 이력을 입력받았다는 점이었다. 같은 정밀 GR 입력을 적용한 저비용 대조에서 원 SSP2 에너지 차이는0.6993%, 운동량 차이는0.00001667%로 줄었다. 전체 구간의 작은 입력 차이가 극히 작은 초기 힘의 상대차를 보장하지는 않았다.

분류: Counterexample candidate. 이후 common-input-plan은 정밀 GR128을 두 적분 시계에 동일하게 적용하는 별도 조건부 실험으로 등록했다. SSP2와 원2% 시간 기준을 유지했다. 이미 같은 입력을 사용했던 정밀128 첫 반환의 광자·물질 전체 이력과 둘째 광자 시범은 SHA로 고정해 그대로 재사용했고, 바뀐64 경로와 남은 반환만 계산했다. 원래 서로 다른 GR 입력의 실패와 SSPRK3 실패는 보존한다. 이 통과가 입력 GR의 불확실성을 제거하거나 원 실패를 통과로 바꾸지는 않는다.

| 반환 | 원 전체 상태 변화 지표 — 감소 기준 실패 |
| --- | ---: |
{table}

분류: Proven. 광자와 총 Etilde/H는 단계 안에서 동시에 푸는 미지수다. 반복의 실제 입력은 B,S,그에 따른 조성 변위와 M=(Etilde,H)-충돌 전달량 C다. 총 E/H와 C에 같은 변화가 생기면 M은 불변이다. 따라서 총 E/H의 반복 간 변화 자체는 실제 전달 입력의 식 잔차와 같지 않다. 이 대수적 구분은 연속계 해의 오차 상계가 아니다.

분류: Counterexample candidate. 둘째 반환의 총 H 변화 지표가121.494%로 커져 사전 중단 조건을 지켰으며 세 번째 진화를 하지 않았다. 저장된 해를 이용한 별도 block-plan 검사에서는 B,S,조성 변위,에너지 좌표 이동,M과 그 구간 도함수,광자·자유 물질 E/H의 일치를 검사했다. 64/128 경로의 모든128/256 SDIRK 단계에서 실제 소유자와 같은 기계적 도함수와 시각을 사용했고, 미지수에 곱하는 선형 연산자가 두 입력에서 동일함을 확인했다. 원천은 광자 에너지/수,기체 에너지/H를 단위별로 따로 정규화했다.

분류: Counterexample candidate. 최대 실제 전달 입력 잔차는{block['maximum_block_defect']:.9g}, 실제 단계 원천 차이는{max(max(r['stage_forcing_defect']) for r in block['rows']):.9g}, 광자·자유 물질 E/H 불일치는{max(max(r['paired_E_H']) for r in block['rows']):.9g}다. 별도 유한 블록 식 일치 기준0.2%를 통과했다. 이 결과로 원 전체 상태 변화/감소 판정을 통과로 고치지 않는다. 아래 전하 판독은 명시된 별도 식 잔차에 조건부이며, 전체 반복 수렴이나 해 오차를 증명하지 않는다.

분류: Counterexample candidate. 최종 광자 시간 차이는{100*max(ph['time_comparison']):.8g}%, 물질 응력 원천 시간 차이는{100*max(src['comparisons']['stress_time']):.8g}%다. 실제 angular 포트·물질 보존·충돌/기계적 일 분리·GR 원천 항등식·수락 prefix 보존 검사를 통과했다. 정규화된 새 원천으로 읽은 계량을 실제 크기로 되돌렸을 때 적용된 자체 계량 대비 최대 잔차는{final['maximum_self_metric_residual']:.9g}다. 이는 유한 모형의 입력 일치 잔차이며, 연속계 수축률이나 해의 엄밀한 오차 상계가 아니다.

분류: Counterexample candidate. 같은 compact 판독기의 실제 결과는 다음과 같다. 아주 작은 보정은 원 값과 별도로 저장해 합산 반올림으로 잃지 않았다.

| 항목 | 값 |
| --- | ---: |
| 자체 GR 반환 전 끝점 | {final['baseline_compact_endpoint']:.12g} |
| 실제 자체 GR 반환 보정 | {final['physical_self_GR_correction_endpoint']:.12g} |
| 기존 끝점 절댓값 대비 부호 있는 보정 | {final['signed_correction_over_baseline']:.9g} |
| 보정 자체의 시간 간격 차이 | {100*final['controls']['time']:.8g}% |
| 보정 자체의 구적 차이 | {100*final['controls']['quadrature']:.8g}% |
| 보정의 독립 직접 trace 차이 | {final['controls']['independent']:.9g} |

분류: Counterexample candidate. 이 표는 지정한 짧은 입사파에 대한 compact 물질 매개 응답이다. 전체 외부 입사파 산란과 외부 광자를 포함한 무한원 전하·관측량은 아니다. 원 응답과 별도로 계산한 보정의 크기 및 그 자체의 시간/구적 오차를 구분한다. 기존 무구동 완화 전하에 더하지 않는다.

분류: Conjectural. 다음 연결은 동일한 외부 입력·실제 방출 이력을 전체 무한원 판독에 넣고 직접 외부장 기여와 물질 매개 기여를 분리하는 것이다. 상위 GR 입력 오차의 최종 전하 영향도 별도로 판정해야 한다. 같은 재고/입력의 완전한 정적 비교와 nuisance 비흡수성, 궤도/관측 연결, 물리 EOS·균일 미분·공간/파형/경계·비선형 오차는 미완료다. 문서의 원 완료 조건을 이번 잔차 통과로 축소하지 않는다.

분류: Counterexample candidate. 다음 판독의 정확도 목표는 다시 지정해야 한다. 단계155의 유한 입력장 higher-return 추정치7.95637797e-18을 eta*r0/M으로 환산하면1.88483175e-42로, 현재 compact 끝점보다 약7.43e8배 큰 척도다. 이는 무한원 오차 상계나 실제 오차 측정값이 아니다. 입사장 대비 작은 잔여 추정치를 훨씬 작은 물질 응답의 분해능으로 곧바로 인정해서는 안 된다. 같은 입력의 직접 기여와 물질 매개 기여를 분리하고, 실제 최종 비교량에 필요한 정확도를 기준으로 계산을 정해야 한다.

운영 기록: action 본문 합계{cost['recorded_action_seconds']:.3f}초, CPU{cost['CPU_seconds']:.3f}초, 최대 RSS{cost['peak_RSS_bytes']/1024**2:.1f}MiB. 1 thread·3GiB 가상 메모리·4600초 합산 한도 안에서 실행했다. 실측 시범과 이전 후기 비용으로 본 계산 진입을 판단하고 수락 prefix를 재사용했다. import·독서·작성·발행/Git 시간은 이 합계에서 제외된다.
'''
    note.write_bytes(text.encode())
    tails={
        'model-definition':'분류: Counterexample candidate. 실제 입사 응답 원천의 자체 GR을 별도 정규화 증분으로 광자·자유 물질에 반환했다. 전체 상태 변화 감소 기준은 실패했다. 실제 전달 입력/모든 단계 원천과 계량 입력의 별도 유한 식 잔차를 수락했다. 초기 GR 계수·17절점·보존 접선 모형 범위다.',
        'observable-targets':'분류: Counterexample candidate. 실제 자체 GR 반환 뒤 compact 전하 보정을 분리 판독했다. 전체 외부 입사파/광자의 무한원 기여와 동일 입력의 정적 비교·관측 식별성은 남아 있다.',
        'adiabatic-limit':'분류: Conjectural. 자체 GR의 실제 반환을 완료한 짧은 펄스 역시 정적·단열·궤도 응답을 대신하지 않는다. 같은 배경/입력의 비교가 필요하다.',
        'nonadiabatic-regime':'분류: Counterexample candidate. 비정상 저장 배경에서 자체 계량을 실제 진화식에 넣고 실제 전달 입력/단계 원천의 유한 식 잔차를 수락했다. 전체 상태 변화 감소 검사는 실패로 보존하며 연속계 수축·전역 미분·오차 상계로 해석하지 않는다.',
        'failure-ledger-dynamic-chi':'분류: Counterexample candidate. stiff 선형 단계의 잔차만 넓은 정밀도로 읽고 상태를 binary64로 되돌리면 보정이 반올림으로 사라질 수 있었다. 단계 상태도 확장 정밀도로 유지했다. 광자 종료 시각이 저장 절점보다1ulp 클 때 다음 구간의 계량 미분을 읽는 결함도 확인해 물질 소유자와 같은 시각 정렬을 적용했다. 원 실패·기준과 영향 없는 prefix를 보존했다.',
        'dynamic-charge-completion':'분류: Counterexample candidate. actual_incident_self_GR_return,finite_block_equation_residual,finite_metric_input_residual,compact_correction_read는true다. original_waveform_change_test_passed,full_nonlinear_Einstein_closure,full_null_infinity_charge,companion_matching,complete_static_comparison,uniform_error_enclosure,observable_identified,full_goal_complete는false다.'}
    prefixes={}
    for name,line in tails.items():
        line+=' 분류: Counterexample candidate. 동일한 정밀 GR128 입력에 조건부인 판정이며, 서로 다른 상위 GR 입력의 초기 비교 실패는 보존한다. 상위 입력 불확실성은 닫히지 않았다.'
        p=root/f'docs/{name}.md';rel=p.relative_to(root).as_posix();raw=p.read_bytes()
        assert sha(p)==data['sha256'][rel] and '## 단계157'.encode() not in raw
        prefixes[rel]=dict(bytes=len(raw),sha256=sha(p))
        with p.open('ab') as f:f.write(('\n\n## 단계157 — 실제 자체 GR 반환\n\n'+line+' [단계157 보고서](../notes/REQUEST157_INCIDENT_SELF_GR_RETURN_KO.md).\n').encode())
    files=[root/f'verification/{m}.py' for m in modules]+[note]+[root/f'docs/{n}.md' for n in tails]+[p for p in out.rglob('*') if p.is_file()]
    summary=dict(classification='Counterexample candidate',passed=True,full_goal_complete=False,
        original_waveform_change_test_passed=False,upstream_GR_uncertainty_closed=False,
        accepted_scope='Fixed-input finite block-equation consistency and compact readout only.',cost=cost,previous_master_sha256=before,
        preserved_phase156_nondoc_files=preserved,preserved_document_prefixes=prefixes,sha256={p.relative_to(root).as_posix():sha(p) for p in files})
    write(manifest,summary);data['sha256'].update(summary['sha256']);data['sha256'][manifest.relative_to(root).as_posix()]=sha(manifest)
    data['native_incident_self_gr']={k:v for k,v in summary.items() if k!='sha256'};write(master,data)


def check(staged=False):
    m=read(manifest);data=read(master)
    for name,h in m['sha256'].items():assert sha(root/name)==h and data['sha256'][name]==h,name
    for name,v in m['preserved_document_prefixes'].items():assert hashlib.sha256((root/name).read_bytes()[:v['bytes']]).hexdigest()==v['sha256']
    assert data['sha256'][manifest.relative_to(root).as_posix()]==sha(manifest)
    paths=list(m['sha256'])+[manifest.relative_to(root).as_posix(),'paper/revision-manifest.json']
    Path('C:/Users/lpaiu/AppData/Local/Temp/native-self-gr-157-paths').write_bytes(b'\0'.join(x.encode() for x in paths)+b'\0')
    if staged:
        actual=subprocess.check_output(['git','diff','--cached','--name-only','-z'],cwd=root).decode().split('\0')
        assert set(filter(None,actual))==set(paths)
        for name in paths:assert hashlib.sha256(subprocess.check_output(['git','show',':'+name],cwd=root)).hexdigest()==sha(root/name),name
    print(json.dumps(dict(bound_files=len(m['sha256']),exact_paths=len(paths),prefixes=6,full_goal_complete=False)))


if __name__=='__main__':
    if sys.argv[1]=='package':package(int(sys.argv[2]))
    check(sys.argv[1]=='staged')
