"""Connect the updated physical trajectory to its compensated GR response."""
from pathlib import Path
from types import FunctionType
import json,signal,sys,time
import numpy as np
import def_native_refined_thermochemistry as physical

flow=physical.flow;C=flow.C;write=flow.write;sha=flow.sha
OUT=physical.OUT/'updated-gr-return';BG=OUT/'background';GR=OUT/'gr';LAPSE=OUT/'lapse';COLL=OUT/'collision';RESPONSE=OUT/'response'


def prepare():
    assert not OUT.exists()
    for p in [BG,GR,LAPSE/'corrected',COLL,RESPONSE]:p.mkdir(parents=True,exist_ok=True)
    write(OUT/'plan.json',dict(classification='Counterexample candidate',checkpoint='ba520aaac',
        claim='Return GR fields generated by the corrected EOS trajectories into the actual shared photon/thermal/H response, then retain these histories for the material/GR fixed-point closure.',
        missing='Phase130 saved all-step moments and terminal states but not the intermediate conservative states/angular spectra required by the existing response owner. Old-EOS snapshots cannot stand in for the updated trajectory.',
        repair='Replay only the two already accepted physical paths once with observational capture, prove their original sources and terminal states unchanged, and immediately consume the recovered states in updated GR/lapse and simultaneous radiation/thermal/H response. Capture actual accepted-stage angular emission, not endpoint trapezoids.',
        reuse='Updated thermal bank and original physical equations,531 cells,8 angles,152 frequencies,3.434ms,64/128 clocks; no extra native states or physical resolution. Keep all17 canonical states and accepted stage angular ports to avoid another diagnostic replay.',
        gates=dict(replay=1e-12,energy=1e-8,exact_port=1e-10,GR_cadence=.002,GR_quadrature=.002,
            time=.02,linear=1e-12,species=1e-8,derivative=.0001),
        budget=dict(capture_pilot_seconds=40,capture_seconds=650,GR_seconds=180,lapse_seconds=90,
            coefficient_seconds=90,response_pilot_seconds=65,response_seconds=650,CPU_threads=1,memory_GB=3),
        forecast='Prior actual two-path production353.30s. Use measured capture prefix relative cost and full measured cost,1.5x margin plus20s under650s. Prior three monolithic responses241.93s; measure updated point/step costs and require2x forecast under650s before dispatch.',
        stop='No automatic additional mesh,clock,horizon,EOS table or iterative sweep. Stop on changed physical replay, budget or acceptance failure. Do not call a single radiation/heat/H response a closed material/GR fixed point.',
        bindings={str(p):sha(p) for p in [Path(__file__),Path(physical.__file__),physical.OUT/'bank.npz',physical.EV/'result.json',physical.EV/'source-64.npz',physical.EV/'source-128.npz',physical.EV/'final-64.npz',physical.EV/'final-128.npz']}))


capture_run=FunctionType(physical.Coupled.run_capture.__code__,dict(physical.Coupled.run_capture.__globals__,OUT=BG),argdefs=physical.Coupled.run_capture.__defaults__)


class Capture(physical.Coupled):
    def run(self,steps,count=None,resume=False):
        self.steps=steps;self.port_file=BG/f'accepted-ports-{steps}.npz'
        self.angular=list(np.load(self.port_file)['angular_luminosity']) if resume else []
        result=capture_run(self,steps,count,resume)
        if result['complete']:self.export()
        return result

    def moment(self,U,I,xb,u,theta,eta):
        value=super().moment(U,I,xb,u,theta,eta);k=len(self.times)
        if k%(self.steps//16)==0:
            np.savez_compressed(BG/f'state-{self.steps}-{k}.npz',U=U,I=I,bulk_I=xb*self.bulk.scale,u=u,
                theta=theta,eta=eta,h=self.h,Pi=self.Pi,mass=self.mass,j=self.j)
        return value

    def radiate(self,*args):
        result=super().radiate(*args);I=result[1].sum(0)
        luminosity=2*np.pi*C*self.area[-1]*(I[-1,self.mu>0]@(self.number*self.E))
        self.angular.append(luminosity)
        np.savez_compressed(self.port_file,angular_luminosity=self.angular,h=flow.old.END/self.steps)
        return result

    def export(self):
        ks=range(0,self.steps+1,self.steps//16);states=[dict(np.load(BG/f'state-{self.steps}-{k}.npz')) for k in ks]
        np.savez_compressed(BG/f'coupled-{self.steps}.npz',snapshot_t=np.linspace(0,flow.old.END,17),
            **{'snapshot_'+key:np.array([r[key] for r in states]) for key in states[0]})
        saved=np.load(physical.EV/f'final-{self.steps}.npz');new=np.load(BG/f'checkpoint-{self.steps}.npz')
        assert all(np.array_equal(saved[key],new[key]) for key in saved.files), 'Captured physical path changed'
        old=np.load(physical.EV/f'source-{self.steps}.npz');current=np.load(BG/f'source-{self.steps}.npz')
        assert all(np.array_equal(old[key],current[key]) for key in old.files),'Captured source changed'
        d=dict(current);selected=np.arange(0,self.steps+1,self.steps//16)
        for key in d:
            if key=='t' or key in physical.capture.KEYS+['metric_stress_erg','inner_cumulative_energy_erg','outer_cumulative_energy_erg']:d[key]=d[key][selected]
        np.savez_compressed(GR/f'source-{self.steps}.npz',**d)
        # Keep all accepted angular emission stages. Their piecewise-constant
        # integral must match the physical radiation owner's cumulative port.
        mu=self.mu[self.mu>0];w=self.w[self.mu>0];h=flow.old.END/self.steps
        energy=h*np.cumsum(np.asarray(self.angular)@(2*w*mu))
        reference=current['outer_cumulative_energy_erg'][1:]
        err=float(np.max(abs(energy-reference))/max(abs(reference[-1]),1.));assert err<1e-12
        write(BG/f'replay-{self.steps}.json',dict(classification='Counterexample candidate',passed=True,
            full_terminal_state_bitwise=True,all_step_source_bitwise=True,canonical_states=17,
            accepted_angular_port_relative=err,background_unchanged=True))


def pilot():
    assert not (OUT/'capture-pilot.json').exists();start=time.monotonic();signal.signal(signal.SIGALRM,flow.old.optical.timeout);signal.alarm(40)
    rows=[Capture().run(n,2) for n in [64,128]]
    prior=json.loads((physical.OUT/'pilot.json').read_text())['paths'];full=json.loads((physical.EV/'result.json').read_text())['seconds']
    ratio=sum(r['seconds'] for r in rows)/sum(r['seconds'] for r in prior);estimate=full*ratio;upper=1.5*estimate+20
    result=dict(classification='Counterexample candidate',paths=rows,forecast_seconds=estimate,upper_seconds=upper,
        eligible=bool(all(r['passed'] for r in rows) and upper<650),seconds=time.monotonic()-start)
    write(OUT/'capture-pilot.json',result);signal.alarm(0);print(json.dumps(result),flush=True)
    if result['eligible']:write(OUT/'capture-execution-plan.json',dict(eligible=True,hard_seconds=650,
        source_sha256=sha(__file__),forecast_seconds=estimate,upper_seconds=upper))


def capture():
    assert not (OUT/'capture-result.json').exists();p=json.loads((OUT/'capture-execution-plan.json').read_text());assert p['eligible'] and sha(__file__)==p['source_sha256']
    start=time.monotonic();signal.signal(signal.SIGALRM,flow.old.optical.timeout);signal.alarm(650);rows=[]
    try:
        for n in [64,128]:
            r=Capture().run(n,resume=True);rows.append(r);assert r['passed']
        write(OUT/'capture-result.json',dict(classification='Counterexample candidate',passed=True,paths=rows,seconds=time.monotonic()-start))
    except Exception as exc:write(OUT/'capture-failure.json',dict(error=repr(exc),completed=rows,seconds=time.monotonic()-start));raise
    finally:signal.alarm(0)


if __name__=='__main__':globals()[sys.argv[1]]()
