/*
 * SPDX-FileCopyrightText: 2024 Guillaume VOISIN (researcher at LUTH, Observatoire de Paris, PSL, CNRS) <guillaume.voisin@obspm.fr> <astro.guillaume.voisin@gmail.com>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/* Provide utility routines for integrate.cpp and integrate_convert.cpp
 *
 * Written by Guillaume Voisin 2021 , LUTh, Observatoire de Paris, PSL Research University, CNRS (guillaume.voisin@obspm.fr astro.guillaume.voisin@google.com)
 */
#ifndef Utilities_integrate_h
# define Utilities_integrate_h


#ifdef MPIMODE
    #include "mpi.h"
#endif
#include "Constants.h"
#include <cmath>
#include "Utilities.h"
#include <valarray>
#include <cstdlib>
#include "Parameters.h"
#include "AllTheories3Bodies.h"
#include "Diagnostics.h"
#include <chrono>
#include <string.h>
#include "Orbital_elements.h"


int Read_resume_file(char * resumefile, valarray<value_type> & rp, valarray<value_type> &rpt, 
                      valarray<value_type> &ri, valarray<value_type> &rit, 
                      valarray<value_type>& ro, valarray<value_type> &rot, 
                      valarray<valarray<value_type>>& r_extra, 
                      valarray<valarray<value_type>>& v_extra);
// resumefile : filename of a file from which the first line is read 
// rp, rpt : position and velocity vector of the pulsar 
// ri, rit : position and velocity vector of the inner WD
// ro, rot : position and velocity vector of the outer WD
// r_extra[0], v_extra[0] : position and vleocity vector of the first extra body. Must be pre-allocated
// The expected format is rp[0] rp[1] rp[2] rpt[0] ... rot[2] r_extra[0][0] ... v_extra[nextra-1][2]


void Compute_integrals_of_motion(value_type *** states, const int n, 
                                 const valarray<value_type>  Ms, 
                                 const valarray<valarray<value_type>>  int_Gg, 
                                 const valarray<valarray<value_type>>  int_gammabar, 
                                 const valarray<valarray<valarray<value_type>>> int_betabar, 
                                 const int integrator_type, 
                                 valarray<valarray<value_type>> & center_of_mass_positions,
                                 valarray<valarray<value_type>> & center_of_mass_impulsions,
                                 valarray<value_type>  & energies, valarray<valarray<value_type>> & angular_momentum);
// !! Angular momentum is only computed at Newtonian level 

void Save_meanlongs(char * fname, valarray<value_type> ts_day, valarray<value_type>  l);
// Used to save to file mean longitudes 



void Save_orbels(char * fname, valarray<value_type> & ts_day, orbel_t ** orbels, int nbody);
// Used to save to file nbody orbital elements

void Count_lines_in_file(char * fname, int & nlines, int & ncomments, int & nempty, int max_line_size=3000);
// Total number of lines in file "fname" = nlines + ncomments + nempty
// Comment character is "#"
// Separating character is " " or "\t" or "\n"

void Read_trajectory(char * fname, int nbody,  valarray<long double> & ts_day, valarray<valarray<valarray<long double>>> &  svs);
// Used to read trajectory files generated by "integrate.exe" 

void Save_traj(char * filename, valarray<value_type> ts_day, valarray<valarray<valarray<value_type>>> trajs);


void Read_orbels(char * fname, int nbody,  valarray<long double> & ts_day, orbel_t ** orbels, int nlines  );
// Used to read trajectory-orbels files generated by "integrate_convert.exe" 


#endif
