#!/usr/bin/env python3
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "manuscript.md"
OUTPUT = ROOT / "main.tex"


def preprocess_math(text: str) -> str:
    return (
        text.replace(r"\[", "$$")
        .replace(r"\]", "$$")
        .replace(r"\(", "$")
        .replace(r"\)", "$")
    )


def pandoc_fragment(text: str) -> str:
    result = subprocess.run(
        ["pandoc", "--from", "markdown+raw_tex", "--to", "latex"],
        input=text,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "pandoc failed")
    return result.stdout.strip()


def parse_document(text: str) -> tuple[str, dict[str, str], str, str]:
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        raise ValueError("manuscript.md must start with a level-1 title")

    title = lines[0][2:].strip()
    metadata: dict[str, str] = {}
    i = 1

    while i < len(lines) and not lines[i].strip():
        i += 1

    while i < len(lines):
        stripped = lines[i].strip()
        if not stripped:
            i += 1
            break
        match = re.match(r"^\*\*([^*]+):\*\*\s*(.*)$", stripped)
        if not match:
            break
        value = match.group(2).strip()
        if value.startswith("`") and value.endswith("`"):
            value = value[1:-1]
        metadata[match.group(1).strip().lower()] = value
        i += 1

    while i < len(lines) and not lines[i].strip():
        i += 1

    if i >= len(lines) or lines[i].strip() != "## Abstract":
        raise ValueError("manuscript.md must contain a '## Abstract' section")
    i += 1

    while i < len(lines) and not lines[i].strip():
        i += 1

    abstract_lines = []
    while i < len(lines):
        if lines[i].strip() == "---":
            i += 1
            break
        abstract_lines.append(lines[i])
        i += 1

    while i < len(lines) and not lines[i].strip():
        i += 1

    body = "\n".join(lines[i:]).strip() + "\n"
    abstract = "\n".join(abstract_lines).strip()
    return title, metadata, abstract, body


def shift_heading_levels(body: str) -> str:
    shifted = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped == "---":
            shifted.append("")
            continue
        if line.startswith("## "):
            shifted.append("# " + re.sub(r"^##\s+(?:\d+\.\s*)?", "", line))
            continue
        if line.startswith("### "):
            shifted.append("## " + re.sub(r"^###\s+(?:\d+\.\d+\s*)?", "", line))
            continue
        if line.startswith("#### "):
            shifted.append(
                "### " + re.sub(r"^####\s+(?:\d+\.\d+\.\d+\s*)?", "", line)
            )
            continue
        shifted.append(line)
    text = "\n".join(shifted)
    text = text.replace(
        "## Selected references (draft; convert to BibTeX before submission)",
        "# Selected references",
    )
    return text


def build_tex(title: str, metadata: dict[str, str], abstract: str, body: str) -> str:
    abstract_tex = pandoc_fragment(preprocess_math(abstract))
    body_tex = pandoc_fragment(preprocess_math(shift_heading_levels(body)))
    body_tex = body_tex.replace(r"\$ \dot{x} \$", r"$\dot{x}$")
    body_tex = body_tex.replace(r"\$ \dot{x}-\gamma \$", r"$\dot{x}-\gamma$")
    status = metadata.get("status", "")
    repo = metadata.get("repository", "")
    date = metadata.get("date", "")

    title_tex = title.replace("&", r"\&")
    repo_tex = repo.replace("_", r"\_")

    note_lines = []
    if status:
        note_lines.append(status)
    if repo:
        note_lines.append(rf"Repository: \texttt{{{repo_tex}}}")
    note_block = ""
    if note_lines:
        note_block = (
            "\\begin{center}\n"
            "\\small\n"
            + "\\\\\n".join(note_lines)
            + "\n\\end{center}\n\n"
        )

    tex = f"""% Auto-generated by paper/build_manuscript.py from paper/manuscript.md.
% Edit the markdown source and rerun the build script.
\\documentclass[11pt]{{article}}

\\usepackage[T1]{{fontenc}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{lmodern}}
\\usepackage{{microtype}}
\\usepackage[margin=1in]{{geometry}}
\\usepackage{{amsmath,amssymb,bm}}
\\usepackage{{hyperref}}
\\usepackage{{xurl}}

\\hypersetup{{
  colorlinks=true,
  linkcolor=blue,
  urlcolor=blue
}}

\\providecommand{{\\tightlist}}{{%
  \\setlength{{\\itemsep}}{{0pt}}%
  \\setlength{{\\parskip}}{{0pt}}%
}}

\\title{{{title_tex}}}
\\author{{}}
\\date{{{date}}}

\\begin{{document}}
\\maketitle

{note_block}\\begin{{abstract}}
{abstract_tex}
\\end{{abstract}}

{body_tex}

\\end{{document}}
"""
    return tex


def main() -> int:
    title, metadata, abstract, body = parse_document(SOURCE.read_text())
    OUTPUT.write_text(build_tex(title, metadata, abstract, body))
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
